#!/usr/bin/env bash

export PATH=$PATH:/julia-1.5.1/bin

# Student submissions
PROB1=/autograder/submission/local.sh
PROB2=/autograder/submission/seeding.sh
PROB3=/autograder/submission/extension.sh

# Reference Solutions
SOL1=/autograder/source/local.sh
SOL2=/autograder/source/seeding.sh
SOL3=/autograder/source/extension.sh

# Reference Directories
PROB1_SEQS=/autograder/source/test_cases/local
PROB2_QUERIES=/autograder/source/test_cases/seeding
PROB3_SEEDS=/autograder/source/test_cases/extension
MATRICES=/autograder/source/matrices
DATABASES=/autograder/source/databases

# Test case commands
PROB1_CMD=/autograder/source/local_tests.txt
PROB2_CMD=/autograder/source/seeding_tests.txt
PROB3_CMD=/autograder/source/extension_tests.txt

declare -a results_array

echo "============ [LOCAL] =============="
while read test_cmd; do
  echo $test_cmd
  arr=(${test_cmd})
  seqs=${arr[0]}
  matrix=${arr[1]}
  penalty=${arr[2]}

  cmd="sh local.sh $seqs $matrix $penalty"

  cd /autograder/submission
  result=`sh $PROB1 $PROB1_SEQS/$seqs $MATRICES/$matrix $penalty`

  cd /autograder/source
  expected=`sh $SOL1 $PROB1_SEQS/$seqs $MATRICES/$matrix $penalty`

  passed=`python3 check_equivalence.py local "$PROB1_SEQS/$seqs" "$MATRICES/$matrix" "$penalty" "$result" "$expected"`
  results_array+=("$passed" "$cmd" "$result" "$expected")
done < $PROB1_CMD

echo "============ [SEEDING] =============="
while read test_cmd; do
  echo $test_cmd
  arr=(${test_cmd})
  db=${arr[0]}
  query=${arr[1]}
  k=${arr[2]}
  threshold=${arr[3]}

  cmd="sh seeding.sh $db $query pam250.m $k $threshold"

  cd /autograder/submission
  result=`sh $PROB2 $DATABASES/$db $PROB2_QUERIES/$query $MATRICES/pam250.m $k $threshold`

  cd /autograder/source
  expected=`sh $SOL2 $DATABASES/$db $PROB2_QUERIES/$query $MATRICES/pam250.m $k $threshold`

  passed=`python3 check_equivalence.py seeding "$result" "$expected"`
  results_array+=("$passed" "$cmd" "$result" "$expected")

done < $PROB2_CMD

echo "============ [EXTENSION] =============="
while read test_cmd; do
  echo $test_cmd
  arr=(${test_cmd})
  db=${arr[0]}
  seeds=${arr[1]}
  x=${arr[2]}
  s=${arr[3]}

  cmd="sh extension.sh $db pam250.m $seeds $x $s"

  cd /autograder/submission
  result=`sh $PROB3 $DATABASES/$db $MATRICES/pam250.m $PROB3_SEEDS/$seeds $x $s`

  cd /autograder/source
  expected=`sh $SOL3 $DATABASES/$db $MATRICES/pam250.m $PROB3_SEEDS/$seeds $x $s`

  passed=`python3 check_equivalence.py extension "$result" "$expected"`
  results_array+=("$passed" "$cmd" "$result" "$expected")

done < $PROB3_CMD

echo "============ [RESULTS SUMMARY] =============="
python3 write_test_results.py "${results_array[@]}"

mv /autograder/source/results.json /autograder/results/results.json
